framework:
    asset_mapper:
        paths:
            - assets/
        missing_import_mode: strict
        extensions:
            css: text/css

when@prod:
    framework:
        asset_mapper:
            paths:
                - assets/
                - node_modules/
            hashed_file_names: false